apiVersion: apps/v1
kind: Deployment
metadata:
  name: baileys-store-prod
  namespace: baileys
  labels:
    app: baileys-store
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: baileys-store
  template:
    metadata:
      labels:
        app: baileys-store
    spec:
      containers:
      - name: baileys-store
        image: ghcr.io/luoarch/baileys-store:latest
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: baileys-config
              key: redis-url
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: baileys-config
              key: mongo-url
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: baileys-config
              key: mongo-database
        - name: BAILEYS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: baileys-secrets
              key: master-key
        - name: SESSION_ID
          valueFrom:
            configMapKeyRef:
              name: baileys-config
              key: session-id
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: baileys-store-service
  namespace: baileys
spec:
  selector:
    app: baileys-store
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: baileys-store-hpa
  namespace: baileys
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: baileys-store-prod
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
